"""
Model router — reads task_routing from config/profiles.yaml.
To change a model: edit profiles.yaml. Do not edit this file for model changes.

Supported providers:
  - openrouter:  Cloud models via OpenRouter API (Phase 1 default)
  - litellm:     Local models via LiteLLM → vLLM / Ollama (Phase 3)

Phase 2: Opik observability — all LLM calls are traced automatically via track_openai wrapper.
"""
import os
import uuid
import json
import yaml
import logging
from enum import Enum
from openai import OpenAI

try:
    from google import genai
    from google.genai import types
except ImportError:
    genai = None
    types = None

logger = logging.getLogger("ModelRouter")

try:
    from src.config import load_settings
except ImportError:
    # If used as a standalone script or in sub-package without sys.path setup
    pass


def _configure_opik():
    """
    Configure Opik SDK based on environment variables.
    Supports both Comet cloud and self-hosted Opik.
    
    Environment variables:
      - OPIK_API_KEY: API key for Comet cloud (optional for self-hosted)
      - OPIK_WORKSPACE: Workspace name (Comet cloud)
      - OPIK_PROJECT_NAME: Project name for trace grouping (default: ai-orchestration)
      - OPIK_URL_OVERRIDE: URL for self-hosted Opik server
    
    Priority:
      1. Self-hosted: OPIK_URL_OVERRIDE (no API key needed)
      2. Comet cloud: OPIK_API_KEY
      3. Local mode: Falls back to local if nothing configured
    """
    try:
        import opik
        
        api_key = os.environ.get("OPIK_API_KEY")
        workspace = os.environ.get("OPIK_WORKSPACE")
        project_name = os.environ.get("OPIK_PROJECT_NAME", "ai-orchestration")
        url_override = os.environ.get("OPIK_URL_OVERRIDE")
        
        if url_override:
            opik.configure(use_local=True, url=url_override)
            logger.info(f"[OPIK] Configured for self-hosted at '{url_override}' project '{project_name}'")
        elif api_key:
            config_kwargs = {
                "api_key": api_key,
                "workspace": workspace,
                "project_name": project_name,
            }
            opik.configure(**config_kwargs)
            logger.info(f"[OPIK] Configured for Comet cloud workspace '{workspace}' project '{project_name}'")
        else:
            opik.configure(use_local=True)
            logger.info("[OPIK] Running in local mode (no URL or API key set)")
    except ImportError:
        logger.warning("[OPIK] opik package not installed — tracing disabled")
    except Exception as e:
        logger.warning(f"[OPIK] Configuration failed: {e} — tracing disabled")


_configure_opik()


class TaskType(str, Enum):
    PLANNING   = "planning"
    CODING     = "coding"
    AGENT_STEP = "agent_step"
    ANALYSIS   = "analysis"
    FAST       = "fast"
    EXECUTE    = "execute"


# Words in the task description that indicate a CODING task
_CODING_KEYWORDS = {
    "implement", "code", "debug", "write", "fix", "refactor",
    "build", "test", "function", "class", "method", "script",
    "program", "develop", "create", "api", "endpoint",
}

# Words that indicate a PLANNING task
_PLANNING_KEYWORDS = {
    "plan", "architect", "design", "strategy", "decide",
    "choose", "evaluate", "assess", "review", "compare",
}

# Words that indicate a FAST/FLASH task
_FAST_KEYWORDS = {
    "fast", "flash", "quick", "speed", "instant", "brief",
}

# Words that indicate an EXECUTE task
_EXECUTE_KEYWORDS = {
    "execute", "run", "perform", "do", "action", "command",
}

# Approximate cost per 1 million tokens (prompt + completion combined).
# Update these values if pricing changes — do not hardcode costs elsewhere.
_COST_PER_1M_TOKENS: dict[str, float] = {
    "thudm/glm-4-plus":               0.14,
    "anthropic/claude-opus-4-5":     15.00,
    "anthropic/claude-sonnet-4-6":    3.00,
    "google/gemini-2.5-flash":        0.15,
    "google/gemini-2.5-flash-lite":   0.075,
    "gemini-2.5-flash":               0.15,
    "gemini-2.5-flash-lite":          0.075,
    "gemini-2.0-flash":               0.10,
    "zhipuai/glm-5-pro":              0.50,
    "default":                        1.00,
}


def _load_yaml_config() -> dict:
    """Load config/profiles.yaml."""
    config_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../../../config/profiles.yaml")
    )
    if os.path.exists(config_path):
        with open(config_path, "r") as f:
            return yaml.safe_load(f) or {}
    return {}


class ModelRouter:
    """
    Routes LLM calls to the correct model and provider based on task type.
    All model names and providers come from config/profiles.yaml.

    Phase 1: provider=openrouter → OpenAI SDK pointed at https://openrouter.ai/api/v1
    Phase 3: provider=lmstudio   → OpenAI SDK pointed to local LMStudio/Ollama API
    """

    def __init__(self):
        try:
            load_settings()
        except Exception:
            pass
        _configure_opik()
        
        config_data = _load_yaml_config()
        self._routing = config_data.get("task_routing", {})
        self._specializations = config_data.get("specializations", {})
        api_key = os.environ.get("OPENROUTER_API_KEY", "")
        if not api_key:
            logger.warning("OPENROUTER_API_KEY not set — OpenRouter calls will fail")
        
        self._openrouter_client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=api_key or "missing-key",
        )
        
        # Native Google Client
        google_api_key = os.environ.get("GOOGLE_API_KEY", "")
        if genai and google_api_key:
            self._google_client = genai.Client(api_key=google_api_key)
            logger.info("[GOOGLE] Native client initialized")
        else:
            self._google_client = None
            if not google_api_key:
                logger.warning("GOOGLE_API_KEY not set — native Google calls will fail")
            if not genai:
                logger.warning("google-genai package not installed — native Google calls will fail")
        
        try:
            from opik.integrations.openai import track_openai
            self._openrouter_client = track_openai(
                self._openrouter_client,
                project_name=os.environ.get("OPIK_PROJECT_NAME", "ai-orchestration")
            )
            logger.info("[OPIK] OpenRouter client wrapped for LLM tracing")
        except ImportError:
            logger.warning("[OPIK] track_openai not available — tracing disabled")
        except Exception as e:
            logger.warning(f"[OPIK] Failed to wrap client: {e}")

    def get_model(self, task_type: TaskType, specialization: str = "general") -> str:
        """
        Return the model string for a task type. Specific specializations override generic types.
        """
        if specialization and specialization != "general":
            spec_conf = self._specializations.get(specialization, {})
            if "model" in spec_conf:
                return spec_conf["model"]

        entry = self._routing.get(task_type.value, {})
        model = entry.get("model")
        if not model:
            logger.warning(f"No model configured for task_type={task_type}, falling back to gemini flash")
            return "google/gemini-2.5-flash"
        return model

    def get_provider(self, task_type: TaskType, specialization: str = "general") -> str:
        """
        Return the provider string for a task type. Missing or generic types rely on defaults.
        """
        if specialization and specialization != "general":
            spec_conf = self._specializations.get(specialization, {})
            if "provider" in spec_conf:
                return spec_conf["provider"]

        entry = self._routing.get(task_type.value, {})
        return entry.get("provider", "openrouter")

    # Reliable fallback used when the configured model is unavailable or invalid.
    # Must be a Google-native model so it routes through _call_google, not OpenRouter.
    SAFE_FALLBACK_MODEL = "gemini-2.5-flash-lite"

    def call_llm(self, messages: list[dict], task_type: TaskType, tools: list, specialization: str = "general") -> tuple:
        """
        Make an LLM call routed to the correct provider.
        Returns (response_message, cost_usd).

        Fallback chain (applied inside this method, transparent to callers):
          1. Configured provider + model  (from profiles.yaml)
          2. If local unavailable         → same model on OpenRouter
          3. If model name invalid (400)  → SAFE_FALLBACK_MODEL on OpenRouter
        Auth (401) and credit (402) errors are re-raised immediately.
        """
        provider = self.get_provider(task_type, specialization)
        model = self.get_model(task_type, specialization)
        is_local = provider in ("lmstudio", "ollama")

        # ── Attempt 1: configured provider ────────────────────────────────
        try:
            if provider == "lmstudio" or provider == "ollama":
                return self._call_local(messages, model, tools)
            elif provider == "google":
                return self._call_google(messages, model, tools)
            else:
                # Default to openrouter
                return self._call_remote(messages, model, tools)
        except Exception as e:
            err = str(e)
            # Hard errors — no fallback makes sense
            if "401" in err or "Unauthorized" in err:
                raise
            if "402" in err or "Payment Required" in err or "credits" in err.lower():
                raise

            if is_local:
                logger.warning(
                    f"[FALLBACK] Local provider '{provider}' unavailable for model '{model}' "
                    f"({err[:120]}). Retrying on OpenRouter."
                )
            else:
                logger.warning(
                    f"[FALLBACK] Model '{model}' failed on '{provider}' "
                    f"({err[:120]}). Will try fallback model."
                )

        # ── Attempt 2: remote with original model (only if we came from local) ──
        if is_local:
            try:
                return self._call_remote(messages, model, tools)
            except Exception as e:
                err = str(e)
                if "401" in err or "Unauthorized" in err:
                    raise
                if "402" in err or "Payment Required" in err or "credits" in err.lower():
                    raise
                logger.warning(
                    f"[FALLBACK] Remote also failed for model '{model}' "
                    f"({err[:120]}). Falling back to safe model '{self.SAFE_FALLBACK_MODEL}'."
                )

        # ── Attempt 3: safe fallback model via Google native client ───────────
        logger.warning(
            f"[FALLBACK] Using safe fallback model '{self.SAFE_FALLBACK_MODEL}' on Google."
        )
        return self._call_google(messages, self.SAFE_FALLBACK_MODEL, tools)

    def _call_remote(self, messages: list[dict], model: str, tools: list) -> tuple:
        """Call a cloud model via OpenRouter. Returns (response_message, cost_usd)."""
        response = self._openrouter_client.chat.completions.create(
            model=model,
            messages=messages,
            tools=tools,
            tool_choice="auto",
        )
        usage = response.usage
        cost = self.compute_cost(model, usage.prompt_tokens, usage.completion_tokens)
        return response.choices[0].message, cost

    def _call_local(self, messages: list[dict], model: str, tools: list) -> tuple:
        """
        Call a local model via a standard OpenAI client pointed to local endpoint.
        """
        config_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../config/settings.yaml"))
        api_base = "http://127.0.0.1:1234/v1"
        if os.path.exists(config_path):
            with open(config_path, "r") as f:
                settings = yaml.safe_load(f)
                env = settings.get("active_environment", "primary")
                lmstudio = settings.get("environments", {}).get(env, {}).get("lmstudio", {})
                if lmstudio:
                    host = lmstudio.get("host", "127.0.0.1")
                    port = lmstudio.get("port", 1234)
                    api_base = f"http://{host}:{port}/v1"
        
        local_client = OpenAI(
            base_url=api_base,
            api_key="local-dummy-key"
        )
        
        try:
            from opik.integrations.openai import track_openai
            local_client = track_openai(
                local_client,
                project_name=os.environ.get("OPIK_PROJECT_NAME", "ai-orchestration")
            )
        except Exception:
            pass
        
        if model.startswith("openai/"):
            model = model.replace("openai/", "")
            
        response = local_client.chat.completions.create(
            model=model,
            messages=messages,
            tools=tools,
            tool_choice="auto",
        )
        return response.choices[0].message, 0.0

    def _call_google(self, messages: list[dict], model: str, tools: list) -> tuple:
        """
        Call a Google model directly via the native google-genai SDK.
        Supports function calling: converts OpenAI-format tool schemas to Google format
        and maps function_call responses back to the OpenAI tool_calls interface.
        Falls back to OpenRouter if the native client is unavailable.
        """
        if not self._google_client:
            logger.warning("[GOOGLE] Native client unavailable — routing through OpenRouter instead.")
            return self._call_remote(messages, f"google/{model}" if not model.startswith("google/") else model, tools)

        # Convert OpenAI-style messages to google-genai Contents
        contents = []
        system_instruction = None
        for m in messages:
            role = m.get("role", "user")
            content = m.get("content", "")
            msg_tool_calls = m.get("tool_calls", [])

            if role == "system":
                system_instruction = content
            elif role == "assistant":
                parts = []
                if content:
                    parts.append(types.Part(text=content))
                # Re-encode assistant tool call turns as function_call parts
                for tc in (msg_tool_calls or []):
                    try:
                        fn_args = json.loads(tc["function"]["arguments"]) if isinstance(tc["function"]["arguments"], str) else tc["function"]["arguments"]
                    except (json.JSONDecodeError, KeyError):
                        fn_args = {}
                    parts.append(types.Part(
                        function_call=types.FunctionCall(
                            name=tc["function"]["name"],
                            args=fn_args,
                        )
                    ))
                if parts:
                    contents.append(types.Content(role="model", parts=parts))
            elif role == "tool":
                # Tool result turns → function_response parts
                tool_call_id = m.get("tool_call_id", "")
                try:
                    result_data = json.loads(content) if content else {}
                    if not isinstance(result_data, dict):
                        result_data = {"output": content}
                except (json.JSONDecodeError, TypeError):
                    result_data = {"output": content or ""}
                # Find the function name from prior assistant message
                fn_name = tool_call_id  # fallback; will be overridden if resolvable
                for prior in reversed(contents):
                    for p in (prior.parts or []):
                        if hasattr(p, "function_call") and p.function_call:
                            fn_name = p.function_call.name
                            break
                    else:
                        continue
                    break
                contents.append(types.Content(role="user", parts=[
                    types.Part(function_response=types.FunctionResponse(
                        name=fn_name,
                        response=result_data,
                    ))
                ]))
            else:
                contents.append(types.Content(role="user", parts=[types.Part(text=content or "")]))

        # Convert OpenAI tool schemas → Google FunctionDeclaration list
        google_tools = None
        if tools:
            fn_decls = []
            for t in tools:
                if t.get("type") != "function":
                    continue
                fn = t["function"]
                params = fn.get("parameters", {})
                fn_decls.append(types.FunctionDeclaration(
                    name=fn["name"],
                    description=fn.get("description", ""),
                    parameters=params if params else None,
                ))
            if fn_decls:
                google_tools = [types.Tool(function_declarations=fn_decls)]

        config_kwargs: dict = {}
        if system_instruction:
            config_kwargs["system_instruction"] = system_instruction
        if google_tools:
            config_kwargs["tools"] = google_tools

        # Strip provider prefix (genai uses bare model IDs)
        bare_model = model.replace("google/", "")

        response = self._google_client.models.generate_content(
            model=bare_model,
            contents=contents,
            config=types.GenerateContentConfig(**config_kwargs) if config_kwargs else None,
        )

        # Token cost
        usage = response.usage_metadata
        prompt_tokens = getattr(usage, "prompt_token_count", 0) or 0
        completion_tokens = getattr(usage, "candidates_token_count", 0) or 0
        cost = self.compute_cost(bare_model, prompt_tokens, completion_tokens)

        # Parse the response — may be text, function calls, or both
        text_parts = []
        tool_call_parts = []

        candidate = response.candidates[0] if response.candidates else None
        if candidate and candidate.content and candidate.content.parts:
            for part in candidate.content.parts:
                if hasattr(part, "function_call") and part.function_call and part.function_call.name:
                    tool_call_parts.append(part.function_call)
                elif hasattr(part, "text") and part.text:
                    text_parts.append(part.text)

        text = "".join(text_parts)

        # Build an object that matches the OpenAI message interface
        class _Msg:
            def __init__(self, text, tool_calls):
                self.content = text
                self.tool_calls = tool_calls or None
                self.role = "assistant"

        class _FunctionCall:
            def __init__(self, name, arguments_str):
                self.name = name
                self.arguments = arguments_str

        class _ToolCall:
            def __init__(self, id_, fn):
                self.id = id_
                self.type = "function"
                self.function = fn

        openai_tool_calls = []
        for fc in tool_call_parts:
            args_str = json.dumps(dict(fc.args)) if fc.args else "{}"
            tc_id = f"call_{uuid.uuid4().hex[:16]}"
            openai_tool_calls.append(_ToolCall(tc_id, _FunctionCall(fc.name, args_str)))

        return _Msg(text, openai_tool_calls if openai_tool_calls else None), cost

    def detect_task_type(self, description: str) -> TaskType:
        """
        Detect task type from task description keywords.
        Priority: CODING keywords > PLANNING keywords > AGENT_STEP (default)
        """
        words = set(description.lower().split())
        if words & _CODING_KEYWORDS:
            return TaskType.CODING
        if words & _PLANNING_KEYWORDS:
            return TaskType.PLANNING
        if words & _EXECUTE_KEYWORDS:
            return TaskType.EXECUTE
        if words & _FAST_KEYWORDS:
            return TaskType.FAST
        return TaskType.AGENT_STEP

    def compute_cost(self, model: str, prompt_tokens: int, completion_tokens: int) -> float:
        """Estimate cost in USD from token usage using the pricing table above."""
        rate = _COST_PER_1M_TOKENS.get(model, _COST_PER_1M_TOKENS["default"])
        return (prompt_tokens + completion_tokens) / 1_000_000 * rate
