"""
Model router — reads task_routing from config/profiles.yaml.
To change a model: edit profiles.yaml. Do not edit this file for model changes.

Supported providers:
  - openrouter:  Cloud models via OpenRouter API (Phase 1 default)
  - litellm:     Local models via LiteLLM → vLLM / Ollama (Phase 3)
"""
import os
import yaml
import logging
from enum import Enum
from openai import OpenAI

logger = logging.getLogger("ModelRouter")


class TaskType(str, Enum):
    PLANNING   = "planning"
    CODING     = "coding"
    AGENT_STEP = "agent_step"
    ANALYSIS   = "analysis"


# Words in the task description that indicate a CODING task
_CODING_KEYWORDS = {
    "implement", "code", "debug", "write", "fix", "refactor",
    "build", "test", "function", "class", "method", "script",
    "program", "develop", "create", "api", "endpoint",
}

# Words that indicate a PLANNING task
_PLANNING_KEYWORDS = {
    "plan", "architect", "design", "strategy", "decide",
    "choose", "evaluate", "assess", "review", "compare",
}

# Approximate cost per 1 million tokens (prompt + completion combined).
# Update these values if pricing changes — do not hardcode costs elsewhere.
_COST_PER_1M_TOKENS: dict[str, float] = {
    "thudm/glm-4-plus":               0.14,
    "anthropic/claude-opus-4-5":     15.00,
    "anthropic/claude-sonnet-4-6":    3.00,
    "google/gemini-2.5-flash":        0.15,
    "google/gemini-2.5-flash-lite":   0.075,
    "default":                        1.00,
}


def _load_task_routing() -> dict:
    """Load the task_routing block from config/profiles.yaml."""
    config_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "../../../config/profiles.yaml")
    )
    with open(config_path, "r") as f:
        data = yaml.safe_load(f)
    routing = data.get("task_routing", {})
    if not routing:
        logger.warning("No task_routing found in profiles.yaml — using safe defaults")
    return routing


class ModelRouter:
    """
    Routes LLM calls to the correct model and provider based on task type.
    All model names and providers come from config/profiles.yaml.

    Phase 1: provider=openrouter → OpenAI SDK pointed at https://openrouter.ai/api/v1
    Phase 3: provider=litellm   → litellm.completion() for local vLLM / Ollama
    """

    def __init__(self):
        self._routing = _load_task_routing()
        # OpenRouter client — used when provider=openrouter in config
        api_key = os.environ.get("OPENROUTER_API_KEY", "")
        if not api_key:
            logger.warning("OPENROUTER_API_KEY not set — OpenRouter calls will fail")
        self._openrouter_client = OpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=api_key or "missing-key",
        )

    def get_model(self, task_type: TaskType) -> str:
        """
        Return the model string for a task type.
        Example: get_model(TaskType.CODING) → "thudm/glm-4-plus"
        """
        entry = self._routing.get(task_type.value, {})
        model = entry.get("model")
        if not model:
            logger.warning(f"No model configured for task_type={task_type}, falling back to gemini flash")
            return "google/gemini-2.5-flash"
        return model

    def get_provider(self, task_type: TaskType) -> str:
        """
        Return the provider string for a task type.
        Returns 'openrouter' or 'litellm'.
        """
        entry = self._routing.get(task_type.value, {})
        return entry.get("provider", "openrouter")

    def call_llm(self, messages: list[dict], task_type: TaskType, tools: list) -> tuple:
        """
        Make an LLM call routed to the correct provider.
        Returns (response_message, cost_usd).

        Dispatches to:
          - _call_openrouter() when provider=openrouter
          - _call_litellm()    when provider=litellm (Phase 3)
        """
        provider = self.get_provider(task_type)
        model = self.get_model(task_type)

        if provider == "litellm":
            # Phase 3: local model via LiteLLM → vLLM
            return self._call_litellm(messages, model, tools)
        else:
            # Phase 1 default: OpenRouter
            return self._call_openrouter(messages, model, tools)

    def _call_openrouter(self, messages: list[dict], model: str, tools: list) -> tuple:
        """Call a cloud model via OpenRouter. Returns (response_message, cost_usd)."""
        response = self._openrouter_client.chat.completions.create(
            model=model,
            messages=messages,
            tools=tools,
            tool_choice="auto",
        )
        usage = response.usage
        cost = self.compute_cost(model, usage.prompt_tokens, usage.completion_tokens)
        return response.choices[0].message, cost

    def _call_litellm(self, messages: list[dict], model: str, tools: list) -> tuple:
        """
        Call a local model via LiteLLM (vLLM / Ollama).
        Phase 3 — LiteLLM is kept in requirements.worker.txt for this purpose.
        """
        import litellm
        response = litellm.completion(
            model=model,
            messages=messages,
            tools=tools,
            tool_choice="auto",
        )
        cost = litellm.completion_cost(completion_response=response) or 0.0
        return response.choices[0].message, cost

    def detect_task_type(self, description: str) -> TaskType:
        """
        Detect task type from task description keywords.
        Priority: CODING keywords > PLANNING keywords > AGENT_STEP (default)
        """
        words = set(description.lower().split())
        if words & _CODING_KEYWORDS:
            return TaskType.CODING
        if words & _PLANNING_KEYWORDS:
            return TaskType.PLANNING
        return TaskType.AGENT_STEP

    def compute_cost(self, model: str, prompt_tokens: int, completion_tokens: int) -> float:
        """Estimate cost in USD from token usage using the pricing table above."""
        rate = _COST_PER_1M_TOKENS.get(model, _COST_PER_1M_TOKENS["default"])
        return (prompt_tokens + completion_tokens) / 1_000_000 * rate
