global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "observability_collector"
    static_configs:
      - targets: ["collector:9091"]

  - job_name: "temporal"
    static_configs:
      - targets: ["temporal:8233"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
