FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install -r requirements.txt

# Replicate the entire codebase to the local worker node
COPY . .

CMD ["python", "central_node/worker.py"]
